### ISSUE TITLE
Missing License?

### ISSUE THREAD

**Issue by davekempe** [Uberspace/icingaweb2-module-netboximport#11]
Hey guys,
we love this tool, and its super handy. We have cloned the repo privately and added some features and fixes we needed. Happy to contribute or fork or whatever, can you please let us know what license you want to use? Thanks for your work in creating it, it has really helped with a few projects.

**Comment by luto** [comment]
Oh.. we seem to have neglected that aspect of the project. Looking at the commits, I also consider @joni1993 an author. What do you think about MIT, @joni1993?

**Comment by joni1993** [comment]
Thank you for considering me as author too. I think MIT is a good choice.

**Comment by luto** [comment]
@davekempe the project is now MIT licensed. I am looking forward to your pull requests! :)
