### ISSUE TITLE
Nautobot also supported?

### ISSUE THREAD

**Issue by zatroa** [Uberspace/icingaweb2-module-netboximport#19]
Is this icingaweb2 module also compatible to the Nautobot API?
https://github.com/nautobot/nautobot

**Comment by joni1993** [comment]
There is no official support - but currently i couldn't find any API related changes in their release notes, so it should work for now.
As it is sometimes hard enough to deal with Netbox's API changes, future support for NetBox AND Nautobot would probably need some code refactoring and somebody to maintain Nautobots API.
