### ISSUE TITLE
Flattening causes Import failure because of Context Data

### ISSUE THREAD

**Issue by joni1993** [Uberspace/icingaweb2-module-netboximport#8]
## Expected Behavior
Import should work.

## Current Behavior
If you try to import data from Netbox 2.4.7 it doesn't allow you to import because of the long names produced by the context_data in netbox like `local_context_data__last_inform__port_table__3__mac_table__0__uptime`.
The Director team doesn't want to increase the limit of the names for performance reasons and also because they think this module shouldn't flatten the data at all because the director supports structured data.

## Possible Solution
A. Don't flatten the data 
B. Dont expose the context_data to Icinga

I did try to disable the flattening in the module but this resulted in probably invalid JSON (see https://github.com/Icinga/icingaweb2-module-director/issues/1711#issuecomment-441006031)

## Steps to Reproduce (for bugs)
See https://github.com/Icinga/icingaweb2-module-director/issues/1711

## Your Environment
* Icinga Web 2 Netboximport version (System - About): 1.0.0
* Director version (System - About): master (e895978ff243c007a2a50a1c34ea54bd5ef59411)
* Icinga Web 2 version and modules (System - About): 2.6.1, icingaweb2-module-netboximport
* Netbox version (System - About): 2.4.7
* Icinga 2 version (`icinga2 --version`): r2.9.2-1
* Operating System and version: Ubuntu 16.04 
* Webserver, PHP versions: Apache (behind nginx reverse), PHP7.2

**Comment by luto** [comment]
The flattening is the kinda-solution to me failing at importing the data as properly structured json :) it seems like you're also hitting problems there.

> Dont expose the context_data to Icinga

I can't find any documentation or even code on `context_data`. Can you expand a bit on what exactly it contains? :) I am probably fine with just dropping it, though.

**Comment by joni1993** [comment]
:grinning:
I dont use the context data by myself in netbox but here is the link to to documentation https://netbox.readthedocs.io/en/stable/additional-features/context-data/

**Comment by luto** [comment]
oooh, it's a netbox feature, of course. I was looking for icinga docs m(
hm, that actually sounds like useful. Maybe just drop all keys which are too long and document that in the README? Would you like to write a small PR? :)

**Comment by joni1993** [comment]
Just dropping the keys sounds wrong to me. Maybe just get rid of the flattening. But I need to get more into your code to understand it fully, because of the way interfaces are merged with the hosts.

**Comment by joni1993** [comment]
PR is out. I decided its probably the best (e.g. easiest :smiley: ) idea just not to flatten the local_context_data and encode it back to JSON, because it essentially is stored as JSON in Netbox.
